version: "3.7"
services:
    mongo_db:
        image: "mongo"
        container_name: mongo_db
        ports:
            - "27017:27017"
        volumes:
            - data:/data/db
        env_file:
            - ./src/mongodb.env
    mongo-seed:
        build: ./src/seeding/
        command: ["node", "seed.ts"]
        depends_on:
            - mongo_db
    app:
        build: ./
        container_name: vaccine_app
        ports:
            - "4000:4000"
        volumes:
            - ./:/app
            - /app/node_modules
        env_file:
            - ./src/.env
        restart: "on-failure"
        command: ["npm", "run", "dev"]
        depends_on:
            - mongo_db
            - mongo-seed
volumes:
    data:
